model:
  name: "resnet18"
  pretrained: true
  num_classes: 8
  unfreeze_modules: ["fc"]

temperature_scaling:
  enabled: false
  temperature: 1.0

data:
  data_dir: "data/Omini_DATA"

train:
  init_model_path: 'models/resnet18.pt'
  epochs: 5
  batch_size: 32
  lr: 0.001
  patience: 3

save:
  path: "models/resnet18V1.pt"
  format: "pt"

dvclive: 
  dir: "dvclive/resnet18"